# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: to_do_list_development
  pool: 5
  username: postgres
  password: postgres
  host: 127.1

test:
  adapter: postgresql
  encoding: unicode
  database: to_do_list_test
  pool: 5
  username: postgres
  password: postgres
  host: 127.1

production:
  adapter: postgresql
  encoding: unicode
  database: to_do_list_production
  pool: 5
  username: postgres

